const products = [
  {
    _id: "1",
    name: "airpod v-2",
    description: "description of the products",
    image: "https://source.unsplash.com/random/300×300",
    brand: "band",
    category: "category",
    rating: "1 ",
    price: 100,
    countInstock: 20,
  },
  {
    _id: "2",
    name: "iphone 23",
    description: "s",
    image: "https://source.unsplash.com/random/300×300",
    brand: "band",
    category: "category",
    rating: "3 ",
    price: 100,
    countInstock: 20,
  },
  {
    _id: "3",
    name: "keptown",
    description: "description of the products",
    image: "https://source.unsplash.com/random/300×300",
    brand: "band",
    category: "category",
    rating: "2 ",
    price: 100,
    countInstock: 20,
  },
  {
    _id: "4",
    name: "normal hub",
    description: "description of the products",
    image: "https://source.unsplash.com/random/300×300",
    brand: "band",
    category: "category",
    rating: "5 ",
    price: 100,
    countInstock: 20,
  },
  {
    _id: "5",
    name: "mett speaker",
    description: "description of the products",
    image: "https://source.unsplash.com/random/300×300",
    brand: "band",
    category: "category",
    rating: "3.6 ",
    price: 100,
    countInstock: 20,
  },
];
export default products;
